enum{
	MMrRipper,

	MExtraction,
	MPath,
    MDoConv,    

    MOverwrite,
    MOverwritePut,

    MYes,
    MNo,
    MYesAll,
    MNoAll,

	MColumnFile,
	MColumnOffset,
	MColumnSize,
	MColumnDescription,

	MOK,
	MCancel,

    MList,

	MScan,
	MScanning,    
	MFound,
	MLastFound,

    MAdd,    
    MAdding,
    MRecompile,
    MRecompileMsg,

	MExtracting,
	MExtr1,
	MExtr2,

	MConfigTitle,
	MConfigDisablePlugin,
	MConfigFullScan,
    MConfigDelDup,
    MUseSomeOffset,
    MUseStartScan,
    MSkipPack,
    MShowScanDialog,
	MConfigPrefix,
	MConfigEnableGraph,
	MConfigEnableVideo,
	MConfigEnableSound,
    MConfigEnableMusic,
    MConfigEnableText,
    MConfigEnableExe,
	MConfigEnablePacks,
	MConfigEnableOther,
	MConfigEnableFormat,
	MScanRange,
	MWholeFile,
	MUserDefined,
	MDefineRange,

	MDefineTitle,
    MDefineStart,
	MDefineLength,
	MDefineEnd,

	MMenuTitle,
	MMenuBottom,

	MF5,
    MF7On,
    MF7Off,
    MF3,    
    MCtrlShiftF3,
    MCtrlF5,
	MCtrlF8,
	MCtrlF9,
	MShiftF4,
	MShiftF3,
	MShiftF2,
	MShiftF1On,
	MShiftF1Off,

    MInfoTitle,
    MInfoOptString,
    MInfoCopyright,
    MInfoPath,
    MInfoType,
    MInfoVer,
    MInfoRipVer,
    MInfoTypeGraph,
    MInfoTypeVideo,
    MInfoTypeSound,
    MInfoTypeMusic,
    MInfoTypeText,
    MInfoTypeExe,
    MInfoTypePack,
    MInfoTypeOther,

    MDelError,
    MDelNotSupportMsg,    
    MSkip,
    MDelErrorMsg,
    MDeleting,
    MConfirmDelete,

    MPackType,
    MRawType,
    MFilesCount,
    MAllSize,

	MAddDummyTitle,
	MDummyName,
	MDummyDesc,
	MDummyOffset,
	MDummySize,
	MDummyEndOffset,

	MSplitTitle,
	MSplitString,
	MSplitSize,
	MSplitOffset,
	MSplitExt,

	MListLoading,
	MListSaving,
	MUseLists,

	MMrRipperList,
    MColumnPlugin,
    MColumnVersion,
    MPMF6,
    MPMF3,
    MPMF7,
    MPMF8,
    MNewPreset,
    MNewPresetCapt,
    MLoadPreset,
    MDefaultPreset,
    MOverwritePreset
};